remote_theme: pages-themes/minimal@v0.2.0
title: "Subbify Bot"
description: "Subbify Bot — это бот для телеграма, который позволяет продавать подписки на любой контент."
show_downloads: false
plugins:
  - jekyll-remote-theme
